-- 코드를 입력하세요
# SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME, I.SEX_UPON_INTAKE, O.SEX_UPON_OUTCOME
# FROM ANIMAL_INS I
# JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
# WHERE I.SEX_UPON_INTAKE LIKE 'Intact%' AND O.SEX_UPON_OUTCOME != I.SEX_UPON_INTAKE
# ORDER BY I.ANIMAL_ID;

SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_OUTS O
LEFT JOIN ANIMAL_INS I ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE LIKE 'Intact%' AND O.SEX_UPON_OUTCOME != I.SEX_UPON_INTAKE
ORDER BY O.ANIMAL_ID;